CREATE OR REPLACE VIEW SM3_CART_VIEW
AS
    SELECT 
        CA.CART_NUM,CA.USER_NUM,CA.SIZE_NUM,CA.ORDER_CNT,
        I.ITEM_ORGIMG,I.ITEM_NAME,I.ITEM_PRICE,
        CO.COLOR_NAME
    FROM SM3_ITEM I,SM3_ITEM_SIZE S,SM3_ITEM_COLOR CO,SM3_CART CA
    WHERE I.ITEM_NUM=S.ITEM_NUM AND S.COLOR_NUM=CO.COLOR_NUM AND S.SIZE_NUM=CA.SIZE_NUM;

CREATE OR REPLACE VIEW SM3_PURCHASE_VIEW
AS
    SELECT 
        P.PL_NUM,P.PUR_NUM,P.SIZE_NUM,P.ORDER_CNT,
        I.ITEM_SAVIMG,I.ITEM_NAME,I.ITEM_PRICE,
        CO.COLOR_NAME
    FROM SM3_ITEM I,SM3_ITEM_SIZE S,SM3_ITEM_COLOR CO,SM3_PURCHASE_LIST P
    WHERE I.ITEM_NUM=S.ITEM_NUM AND S.COLOR_NUM=CO.COLOR_NUM AND S.SIZE_NUM=P.SIZE_NUM;