CREATE OR REPLACE VIEW SM3_ITEM_VIEW
AS
    SELECT 
        C.CATE_NUM,C.CATE_NAME,
        I.ITEM_NUM,I.ITEM_NAME,I.ITEM_INFO,I.ITEM_PRICE,I.ITEM_ORGIMG,I.ITEM_SAVIMG,
        S.SIZE_NUM,S.SIZE_NAME,S.SIZE_CNT,
        CO.COLOR_NUM,CO.COLOR_NAME,CO.COLOR_CODE
    FROM SM3_ITEMCATE C,SM3_ITEM I,SM3_ITEM_SIZE S,SM3_ITEM_COLOR CO
    WHERE C.CATE_NUM=I.CATE_NUM AND I.ITEM_NUM=S.ITEM_NUM AND S.COLOR_NUM=CO.COLOR_NUM;